In [3]:
def squares(values):
  result = []
  for v in values:
    result.append(v*v)
    return result

In [4]:
to_square = range(100000)

In [5]:
%timeit squares(to_square)

355 ns ± 13.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
import numpy as np
array_to_square = np.arange(0,100000)

In [7]:
%timeit array_to_square **2

148 µs ± 6.38 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
a = np.array([33,44,55])

In [9]:
a

array([33, 44, 55])

In [10]:
type(a)

numpy.ndarray

In [11]:
np.size(a)

3

In [14]:
len(a)

3

In [15]:
a2 = np.array([1,2,3,4,5.5],dtype=int)
a2

array([1, 2, 3, 4, 5])

In [16]:
a3 = np.array([0]*10)
a3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
q= np.ones(5)
q

array([1., 1., 1., 1., 1.])

In [23]:
np.zeros_like(q)

array([0., 0., 0., 0., 0.])

In [24]:
np.linspace(0,100,10000)

array([0.00000000e+00, 1.00010001e-02, 2.00020002e-02, ...,
       9.99799980e+01, 9.99899990e+01, 1.00000000e+02])

In [0]:
_2darray= np.array([[1,2,4,3],[5,6,7,8],[2,3,4,5],[1,2,3,4]])

In [28]:
_2darray

array([[1, 2, 4, 3],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [1, 2, 3, 4]])

In [29]:
np.size(_2darray)

16

In [30]:
len(_2darray)

4

In [31]:
_2darray.shape

(4, 4)

In [0]:
_2darray =np.arange(25).reshape(5,5)

In [33]:
_2darray

array([[1, 2, 4, 3],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [1, 2, 3, 4]])

In [36]:
np.size(_2darray)

25

In [37]:
np.size(_2darray,0)

5

In [38]:
np.size(_2darray,1)

5

In [39]:
_2darray.shape

(5, 5)

In [40]:
len(_2darray)

5

In [16]:
_2darray.reshape(20)

array([ 0.27328644, -0.99996235, -0.28530202,  0.17669212,  1.87916485,
        0.6091629 , -0.82045958,  1.68702267, -1.36467934, -1.55502477,
        0.14632968,  1.03995667, -2.89713572, -1.47083226,  0.5357277 ,
       -0.75169223,  0.38307916, -0.34543423, -1.77717427,  1.00249949])

In [27]:
_2darray = np.random.randn(20).reshape(5,4)

In [28]:
_2darray

array([[-0.78085832,  2.60445011, -1.28388031, -0.32772126],
       [ 0.35973192,  0.73889142, -0.30596267, -0.07745256],
       [-0.44074485,  1.22349866, -1.99457711,  1.7142134 ],
       [-0.02188377, -0.89220309,  2.77526386,  0.48634004],
       [ 0.76056862,  1.59451334,  1.288279  ,  0.87493981]])

In [29]:
_2darray = np.arange(20).reshape(4,5)

In [30]:
_2darray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
_2darray[0:2,3:]

array([[3, 4],
       [8, 9]])

In [31]:
_2darray[3,2]

17

In [32]:
_2darray[1,3]

8

In [24]:
_2darray[3,4]

19

In [25]:
_2darray[2,4]

14

In [26]:
_2darray[0,0]

0

In [33]:
_2darray[1,]

array([5, 6, 7, 8, 9])

In [34]:
_2darray[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [35]:
_2darray[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [36]:
_2darray[0:4,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [40]:
print(_2darray)
_2darray[1:3,3:5]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 8,  9],
       [13, 14]])

In [41]:
_2darray[:,4]

array([ 4,  9, 14, 19])

In [42]:
_2darray[:,1]

array([ 1,  6, 11, 16])

In [43]:
_2darray[3,]

array([15, 16, 17, 18, 19])

In [44]:
_2darray[3:4,0:5]

array([[15, 16, 17, 18, 19]])

In [45]:
p = _2darray[3,:]
p

array([15, 16, 17, 18, 19])

In [46]:
p[4]=20

In [47]:
p

array([15, 16, 17, 18, 20])

In [48]:
_2darray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 20]])

In [49]:
d3 = np.arange(100).reshape(5,5,4)

In [50]:
d3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [51]:
d3[2:4,2:4,1:3]

array([[[49, 50],
        [53, 54]],

       [[69, 70],
        [73, 74]]])

In [52]:
a = np.array([[[[[[[[[[10]]]]]]]]]])

In [53]:
a

array([[[[[[[[[[10]]]]]]]]]])

In [54]:
a.ndim

10

In [55]:
a = np.arange(5)

In [56]:
a

array([0, 1, 2, 3, 4])

In [57]:
a>3

array([False, False, False, False,  True])

In [59]:
_2darray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 20]])

In [61]:
_2darray [[0,2,3],:]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 20]])

In [4]:
import numpy as np

In [18]:
m = np.arange(10,19).reshape(3, 3)

In [19]:
print (m)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [11]:
print ("{0} min of the entire matrix".format(m.min()))

10 min of the entire matrix


In [12]:
print ("{0} max of the entire matrix".format(m.max()))

18 max of the entire matrix


In [13]:
print ("{0} position of the min value".format(m.argmin()))

0 position of the min value


In [14]:
print ("{0} position of the max value".format(m.argmax()))

8 position of the max value


In [15]:
print ("{0} mins down each column".format(m.min(axis = 0)))

[10 11 12] mins down each column


In [16]:
print ("{0} mins across each row".format(m.min(axis = 1)))

[10 13 16] mins across each row


In [17]:
print ("{0} maxs down each column".format(m.max(axis = 0)))

[16 17 18] maxs down each column


In [24]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a.mean()

4.5

In [26]:
a.var()

8.25

In [27]:
a.std()

2.8722813232690143

In [28]:
a.sum()

45

In [29]:
a.prod()

0

In [30]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [31]:
a.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [33]:
a = np.arange(12).reshape(3,4)

In [34]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
np.hsplit(a,4)

[array([[0],
        [4],
        [8]]), array([[1],
        [5],
        [9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]

In [36]:
np.hsplit(a,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [37]:
np.hsplit(a,[1,3])

[array([[0],
        [4],
        [8]]), array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]), array([[ 3],
        [ 7],
        [11]])]

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
array = np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
np.zeros_like(array)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [6]:
np.empty((2,3,2))

array([[[6.23042070e-307, 4.67296746e-307],
        [1.69121096e-306, 1.37961641e-306],
        [1.11260891e-306, 8.01092457e-307]],

       [[7.56599807e-307, 8.90104239e-307],
        [1.24610383e-306, 1.78018403e-306],
        [1.11260551e-306, 2.22522596e-306]]])

In [7]:
a = np.ones((4,5))

In [8]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
a*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [10]:
full = np.full((4,5),5)

In [11]:
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [12]:
s = np.arange(9).reshape(3,3)

In [13]:
s

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
s[:2, 1:]

array([[1, 2],
       [4, 5]])

In [15]:
s[1: ,:2]

array([[3, 4],
       [6, 7]])

In [16]:
s[2], s[2, :], s[2:, :]

(array([6, 7, 8]), array([6, 7, 8]), array([[6, 7, 8]]))

In [17]:
s[:, :2]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [18]:
names = np.array(["bob","joe","will","bob","will","joe","joe"])

In [19]:
data = np.random.randn(7,4)

In [20]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [21]:
data

array([[ 0.42173295, -0.54232732, -1.07512988,  0.183796  ],
       [-0.5691161 , -0.03873246, -1.55098337,  0.66943517],
       [ 0.12767321, -0.34955175,  0.97156849, -1.05461163],
       [ 1.2095908 ,  0.19224806,  0.03214611,  1.30174446],
       [ 1.15046649, -1.29206956,  0.41641542,  0.68515322],
       [-1.00243796,  0.20080783,  0.44675593,  0.83524043],
       [ 1.35018191, -1.6821041 ,  0.85548898,  1.82178759]])

In [22]:
print(names=="bob")

[ True False False  True False False False]


In [23]:
data[names=="bob"]

array([[ 0.42173295, -0.54232732, -1.07512988,  0.183796  ],
       [ 1.2095908 ,  0.19224806,  0.03214611,  1.30174446]])

In [24]:
data[names == "bob",2:]

array([[-1.07512988,  0.183796  ],
       [ 0.03214611,  1.30174446]])

In [25]:
data[names == "bob",3:]

array([[0.183796  ],
       [1.30174446]])

In [26]:
names != "bob"

array([False,  True,  True, False,  True,  True,  True])

In [28]:
data[~(names =="bob")]

array([[-0.5691161 , -0.03873246, -1.55098337,  0.66943517],
       [ 0.12767321, -0.34955175,  0.97156849, -1.05461163],
       [ 1.15046649, -1.29206956,  0.41641542,  0.68515322],
       [-1.00243796,  0.20080783,  0.44675593,  0.83524043],
       [ 1.35018191, -1.6821041 ,  0.85548898,  1.82178759]])

In [29]:
arr = np.arange(15).reshape((3,5))

In [30]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [32]:
arr = np.arange(16).reshape((2,2,4))

In [33]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [34]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [35]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [36]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [37]:
mat1 =  np.arange(12).reshape(3,4)
mat2 = np.array([[4,5,6,7],[3,4,5,6],[9,7,6,5]])

In [38]:
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
mat2

array([[4, 5, 6, 7],
       [3, 4, 5, 6],
       [9, 7, 6, 5]])

In [40]:
mat1 * mat2

array([[ 0,  5, 12, 21],
       [12, 20, 30, 42],
       [72, 63, 60, 55]])

In [41]:
mat3 = np.array([[4,5,6,7],[3,4,5,6],[9,7,6,5],[3,2,6,8]])

In [42]:
mat1@mat3

array([[ 30,  24,  35,  40],
       [106,  96, 127, 144],
       [182, 168, 219, 248]])

In [43]:
np.dot(mat1,mat3)

array([[ 30,  24,  35,  40],
       [106,  96, 127, 144],
       [182, 168, 219, 248]])

In [44]:
from numpy.linalg import inv, qr

In [46]:
x=np.random.rand(5,5)

In [48]:
x

array([[0.50109135, 0.0235229 , 0.42481101, 0.75609813, 0.8647397 ],
       [0.84247042, 0.76967251, 0.9977126 , 0.95790518, 0.5515239 ],
       [0.09499256, 0.76124249, 0.85569287, 0.60184009, 0.2189546 ],
       [0.05592994, 0.88355223, 0.82483782, 0.21224045, 0.74489899],
       [0.8186485 , 0.30756146, 0.53386938, 0.22063717, 0.58595178]])

In [51]:
mat = x.T.dot(x)

In [52]:
mat

array([[1.64318606, 1.03372757, 1.61788143, 1.43554622, 1.44010592],
       [1.03372757, 2.04769783, 2.32227946, 1.46859016, 1.44988487],
       [1.61788143, 2.32227946, 2.87347905, 2.08475852, 2.03221375],
       [1.43554622, 1.46859016, 2.08475852, 1.94520497, 1.60129176],
       [1.44010592, 1.44988487, 2.03221375, 1.60129176, 1.99810847]])

In [53]:
inv(mat)

array([[  4.41156008,  12.67181895, -16.01566511,   3.29031509,
          1.27756232],
       [ 12.67181895,  68.68646603, -87.74194432,  23.25539571,
         11.62873956],
       [-16.01566511, -87.74194432, 114.12960967, -31.18974615,
        -15.87096376],
       [  3.29031509,  23.25539571, -31.18974615,  10.83131553,
          3.79563283],
       [  1.27756232,  11.62873956, -15.87096376,   3.79563283,
          4.24156984]])

In [55]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -7.10542736e-15,  0.00000000e+00,
        -8.88178420e-16,  0.00000000e+00],
       [ 1.99840144e-15,  1.00000000e+00, -1.06581410e-14,
         1.42108547e-14,  6.21724894e-15],
       [ 2.66453526e-15,  2.84217094e-14,  1.00000000e+00,
         9.76996262e-15,  1.06581410e-14],
       [ 0.00000000e+00,  7.10542736e-15,  2.48689958e-14,
         1.00000000e+00, -2.66453526e-15],
       [ 0.00000000e+00,  2.48689958e-14,  3.55271368e-15,
        -8.88178420e-16,  1.00000000e+00]])