In [3]:
def squares(values):
  result = []
  for v in values:
    result.append(v*v)
    return result

In [4]:
to_square = range(100000)

In [5]:
%timeit squares(to_square)

355 ns ± 13.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
import numpy as np
array_to_square = np.arange(0,100000)

In [7]:
%timeit array_to_square **2

148 µs ± 6.38 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
a = np.array([33,44,55])

In [9]:
a

array([33, 44, 55])

In [10]:
type(a)

numpy.ndarray

In [11]:
np.size(a)

3

In [14]:
len(a)

3

In [15]:
a2 = np.array([1,2,3,4,5.5],dtype=int)
a2

array([1, 2, 3, 4, 5])

In [16]:
a3 = np.array([0]*10)
a3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
q= np.ones(5)
q

array([1., 1., 1., 1., 1.])

In [23]:
np.zeros_like(q)

array([0., 0., 0., 0., 0.])

In [24]:
np.linspace(0,100,10000)

array([0.00000000e+00, 1.00010001e-02, 2.00020002e-02, ...,
       9.99799980e+01, 9.99899990e+01, 1.00000000e+02])

In [0]:
_2darray= np.array([[1,2,4,3],[5,6,7,8],[2,3,4,5],[1,2,3,4]])

In [28]:
_2darray

array([[1, 2, 4, 3],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [1, 2, 3, 4]])

In [29]:
np.size(_2darray)

16

In [30]:
len(_2darray)

4

In [31]:
_2darray.shape

(4, 4)

In [0]:
_2darray =np.arange(25).reshape(5,5)

In [33]:
_2darray

array([[1, 2, 4, 3],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [1, 2, 3, 4]])

In [36]:
np.size(_2darray)

25

In [37]:
np.size(_2darray,0)

5

In [38]:
np.size(_2darray,1)

5

In [39]:
_2darray.shape

(5, 5)

In [40]:
len(_2darray)

5

In [16]:
_2darray.reshape(20)

array([ 0.27328644, -0.99996235, -0.28530202,  0.17669212,  1.87916485,
        0.6091629 , -0.82045958,  1.68702267, -1.36467934, -1.55502477,
        0.14632968,  1.03995667, -2.89713572, -1.47083226,  0.5357277 ,
       -0.75169223,  0.38307916, -0.34543423, -1.77717427,  1.00249949])

In [27]:
_2darray = np.random.randn(20).reshape(5,4)

In [28]:
_2darray

array([[-0.78085832,  2.60445011, -1.28388031, -0.32772126],
       [ 0.35973192,  0.73889142, -0.30596267, -0.07745256],
       [-0.44074485,  1.22349866, -1.99457711,  1.7142134 ],
       [-0.02188377, -0.89220309,  2.77526386,  0.48634004],
       [ 0.76056862,  1.59451334,  1.288279  ,  0.87493981]])

In [29]:
_2darray = np.arange(20).reshape(4,5)

In [30]:
_2darray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
_2darray[0:2,3:]

array([[3, 4],
       [8, 9]])

In [31]:
_2darray[3,2]

17

In [32]:
_2darray[1,3]

8

In [24]:
_2darray[3,4]

19

In [25]:
_2darray[2,4]

14

In [26]:
_2darray[0,0]

0

In [33]:
_2darray[1,]

array([5, 6, 7, 8, 9])

In [34]:
_2darray[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [35]:
_2darray[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [36]:
_2darray[0:4,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [40]:
print(_2darray)
_2darray[1:3,3:5]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 8,  9],
       [13, 14]])

In [41]:
_2darray[:,4]

array([ 4,  9, 14, 19])

In [42]:
_2darray[:,1]

array([ 1,  6, 11, 16])

In [43]:
_2darray[3,]

array([15, 16, 17, 18, 19])

In [44]:
_2darray[3:4,0:5]

array([[15, 16, 17, 18, 19]])

In [45]:
p = _2darray[3,:]
p

array([15, 16, 17, 18, 19])

In [46]:
p[4]=20

In [47]:
p

array([15, 16, 17, 18, 20])

In [48]:
_2darray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 20]])

In [49]:
d3 = np.arange(100).reshape(5,5,4)

In [50]:
d3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [51]:
d3[2:4,2:4,1:3]

array([[[49, 50],
        [53, 54]],

       [[69, 70],
        [73, 74]]])

In [52]:
a = np.array([[[[[[[[[[10]]]]]]]]]])

In [53]:
a

array([[[[[[[[[[10]]]]]]]]]])

In [54]:
a.ndim

10

In [55]:
a = np.arange(5)

In [56]:
a

array([0, 1, 2, 3, 4])

In [57]:
a>3

array([False, False, False, False,  True])

In [59]:
_2darray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 20]])

In [61]:
_2darray [[0,2,3],:]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 20]])